import React, { useEffect, useState, type ErrorInfo, type ReactNode } from "react";
import { Link, NavLink, Outlet, useLocation } from "react-router-dom";
import { BriefcaseBusiness, ChevronDown, Flag, Home, Menu, MessageCircle, Search, Settings, ShieldCheck, Store, UserRound, X } from "lucide-react";
import { getRequestRole, useMvpStore } from "../../stores/mvp-store";

const nav=[{to:"/",label:"Inicio",icon:Home,end:true},{to:"/search",label:"Buscar",icon:Search},{to:"/requests",label:"Conversaciones",icon:MessageCircle},{to:"/formalization",label:"Formalización",icon:BriefcaseBusiness},{to:"/me",label:"Mi perfil",icon:UserRound}];
class RouteErrorBoundary extends React.Component<{children:ReactNode},{error:Error|null}>{declare readonly props:{children:ReactNode};state:{error:Error|null}={error:null};static getDerivedStateFromError(error:Error){return{error}}componentDidCatch(error:Error,info:ErrorInfo){if(import.meta.env.DEV)console.error("Route render failed",error,info)}render(){if(this.state.error)return <section className="content-page"><div className="empty-state"><h1>No pudimos mostrar esta página</h1><p>Ocurrió un problema inesperado. Volvé al inicio e intentá nuevamente.</p><Link className="button primary" to="/">Volver al inicio</Link></div></section>;return this.props.children}}

export default function RootLayout(){
  const [open,setOpen]=useState(false);const [account,setAccount]=useState(false);const toast=useMvpStore(state=>state.toast);const setToast=useMvpStore(state=>state.setToast);const current=useMvpStore(state=>state.currentUser);const requests=useMvpStore(state=>state.requests);const location=useLocation();const unread=requests.filter(request=>getRequestRole(request,current)).reduce((sum,request)=>sum+(getRequestRole(request,current)==="provider"?request.unreadByProvider:request.unreadByRequester),0);
  useEffect(()=>{setOpen(false);setAccount(false)},[location.pathname]);useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(null),3500);return()=>clearTimeout(timer)},[toast,setToast]);
  return <div className="app-shell"><header className="topbar"><Link to="/" className="brand" aria-label="Conecta Emprende, inicio"><span className="brand-mark"><Store/></span><span>Conecta <strong>Emprende</strong></span></Link><nav className={open?"main-nav open":"main-nav"}>{nav.map(({to,label,icon:Icon,end})=><NavLink end={end} to={to} key={to} className={({isActive})=>isActive?"active":""}><Icon/>{label}{to==="/requests"&&unread>0&&<span className="nav-unread">{unread}</span>}</NavLink>)}</nav><div className="account-wrap"><button className="account-button" onClick={()=>setAccount(!account)} aria-expanded={account}><span>MR</span><span className="account-copy"><strong>{current.name}</strong><small>{current.role==="ADMIN"?"Administrador":"Proveedor"}</small></span><ChevronDown/></button>{account&&<div className="account-menu"><Link to="/settings/security"><Settings/> Configuración y seguridad</Link>{current.role==="ADMIN"&&<Link to="/admin/reports"><Flag/> Reportes</Link>}<Link to="/trust"><ShieldCheck/> Cómo funciona la confianza</Link><button disabled>Cerrar sesión (demo)</button></div>}</div><button className="menu-button" onClick={()=>setOpen(!open)} aria-label="Abrir navegación">{open?<X/>:<Menu/>}</button></header><main className="app-content"><RouteErrorBoundary key={location.pathname}><Outlet/></RouteErrorBoundary></main>{toast&&<div className="toast" role="status"><ShieldCheck/>{toast}</div>}</div>;
}
