import { Award, BadgeCheck, Check, CheckCircle2, Clock3, LockKeyhole, ShieldCheck, Smartphone, UserRound } from "lucide-react";
import { PageHeader, UnavailableForMvpCard } from "../components/mvp/Ui";
import { useAuthenticatedUser } from "../hooks/use-current-user";
import { useAuthStore } from "../stores/auth-store";

const medalRules=[["Perfil completo","Nombre, ciudad, categoría, descripción, precio y disponibilidad."],["Teléfono verificado","El número de contacto fue confirmado."],["Trabajo confirmado","Completó solicitudes con confirmación bilateral."],["En camino a MIPYME","Avanzó en la guía de formalización."],["Confianza alta","Alcanzó 80 puntos o más con actividad verificada."]];
export function TrustPage(){return <div className="content-page"><PageHeader eyebrow="Reglas transparentes" title="La confianza no es solo una estrella" description="Identidad y reputación se muestran por separado para reducir la inflación del puntaje."/><div className="trust-explainer"><section><BadgeCheck/><h2>Verificación</h2><p>Confirma señales de la cuenta: correo, teléfono y perfil completo.</p></section><section><ShieldCheck/><h2>Reputación</h2><p>Solo cuenta actividad completada entre ambas partes y reseñas vinculadas a solicitudes reales.</p></section><section><Clock3/><h2>Antigüedad</h2><p>0–7 días aplica factor 0.2; 7–30, 0.5; 30–90, 0.8; y 90 días o más, 1.0.</p></section></div><section className="content-section"><h2>Cómo se calcula</h2><p>Teléfono y perfil aportan hasta 15 puntos cada uno; respuestas hasta 20; trabajos confirmados hasta 30; y reseñas verificadas hasta 20. La antigüedad limita el resultado final.</p></section><section className="content-section"><h2>Medallas y reglas</h2><div className="rule-list">{medalRules.map(([name,rule])=><div key={name}><Award/><span><strong>{name}</strong>{rule}</span></div>)}</div></section><section className="content-section"><h2>Protecciones</h2><ul className="check-list"><li><Check/> Solo se completa cuando cliente y proveedor confirman desde sesiones distintas.</li><li><Check/> Una reseña requiere solicitud completada y queda vinculada a su identificador interno.</li><li><Check/> La sesión no se serializa junto con perfiles o solicitudes.</li><li><Check/> Los permisos administrativos vienen del backend, no de un selector local.</li></ul></section></div>}

export function SecurityPage(){const current=useAuthenticatedUser();const session=useAuthStore(state=>state.session);const clear=useAuthStore(state=>state.clearSession);return <div className="content-page"><PageHeader eyebrow="Configuración" title="Seguridad de la cuenta" description="Identidad, perfiles y permisos se mantienen separados para que la sesión pueda venir del login real."/><div className="settings-list"><section><div><Smartphone/><span><h2>Teléfono</h2><p>{current.phoneVerified?"Número verificado":"Pendiente de verificación"}</p></span></div><span className="status status-completed"><CheckCircle2/> {current.phoneVerified?"Verificado":"Pendiente"}</span></section><section><div><UserRound/><span><h2>Perfiles vinculados</h2><p>{current.providerId?"Proveedor":"Sin perfil de proveedor"} · {current.clientProfileId?"Cliente":"Puede comprar con su cuenta base"}</p></span></div><span className="badge">Cuenta única</span></section><section><div><ShieldCheck/><span><h2>Permisos del sistema</h2><p>{session?.systemRoles.join(", ")||"REQUESTER"}</p></span></div><span className="badge">Emitidos por servidor</span></section><section><div><LockKeyhole/><span><h2>Sesión actual</h2><p>Vence {session?new Date(session.expiresAt).toLocaleString("es-NI"):"al cerrar sesión"}</p></span></div><button className="button secondary" onClick={clear}>Cerrar sesión</button></section></div><UnavailableForMvpCard title="Gestión de dispositivos y 2FA pendiente de backend"/></div>}
