import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { Link, useParams } from "react-router-dom";
import { AlertTriangle, ArrowLeft, BadgeCheck, BriefcaseBusiness, Check, CheckCheck, ChevronDown, Circle, Clock3, FileText, Flag, HandCoins, Info, MessageCircle, Search, Send, ShieldCheck, UserRound, X } from "lucide-react";
import { useMvpStore } from "../stores/mvp-store";
import { RequestStatusBadge } from "../components/mvp/Ui";
import type { ChatMessage } from "../lib/mvp-data";

const quickReplies={provider:["Gracias por escribir. ¿Podés compartir cantidad y fecha deseada?","Tengo disponibilidad esta semana.","Puedo enviarte una cotización con precio y entrega."],requester:["Quisiera una cotización detallada.","Te comparto cantidad, medidas y fecha de entrega.","¿Qué información necesitás para cotizar?"]};

export default function ChatPage(){
  const {requestId}=useParams();
  const requests=useMvpStore(state=>state.requests); const providers=useMvpStore(state=>state.providers); const offers=useMvpStore(state=>state.offers); const current=useMvpStore(state=>state.currentUser);
  const addMessage=useMvpStore(state=>state.addMessage); const sendQuote=useMvpStore(state=>state.sendQuote); const acceptQuote=useMvpStore(state=>state.acceptQuote); const confirm=useMvpStore(state=>state.confirmRequest); const close=useMvpStore(state=>state.closeRequest); const markRead=useMvpStore(state=>state.markConversationRead); const addReport=useMvpStore(state=>state.addReport);
  const request=requests.find(item=>item.id===requestId); const provider=providers.find(item=>item.id===request?.providerId); const offer=offers.find(item=>item.id===request?.productId);
  const [actor,setActor]=useState<"provider"|"requester">("provider"); const [reply,setReply]=useState(""); const [search,setSearch]=useState(""); const [unreadOnly,setUnreadOnly]=useState(false); const [quoteOpen,setQuoteOpen]=useState(false); const [price,setPrice]=useState(request?.quotedPriceLabel||""); const [delivery,setDelivery]=useState(request?.quotedDeliveryTime||""); const [externalOpen,setExternalOpen]=useState(false); const [reportOpen,setReportOpen]=useState(false); const [reportText,setReportText]=useState(""); const bottomRef=useRef<HTMLDivElement>(null);
  const conversations=useMemo(()=>requests.filter(item=>!unreadOnly||(item.unreadByProvider+item.unreadByRequester)>0).filter(item=>{const related=providers.find(providerItem=>providerItem.id===item.providerId);return `${item.title} ${related?.publicName||""}`.toLowerCase().includes(search.toLowerCase());}).sort((a,b)=>new Date(b.updatedAt).getTime()-new Date(a.updatedAt).getTime()),[requests,providers,search,unreadOnly]);
  useEffect(()=>{if(requestId)markRead(requestId,actor);},[requestId,actor,markRead]);
  useEffect(()=>{bottomRef.current?.scrollIntoView({behavior:"smooth"});},[request?.messages.length]);
  if(!request||!provider)return <div className="content-page"><h1>Conversación no encontrada</h1><Link className="button primary" to="/requests">Volver a solicitudes</Link></div>;
  const submit=(event:FormEvent)=>{event.preventDefault();if(!reply.trim())return;addMessage(request.id,reply.trim(),actor);setReply("");};
  const submitQuote=(event:FormEvent)=>{event.preventDefault();if(!price.trim()||!delivery.trim())return;sendQuote(request.id,price.trim(),delivery.trim());setQuoteOpen(false);};
  return <div className="chat-page">
    <aside className="chat-conversations">
      <div className="chat-sidebar-head"><Link to="/requests" className="back-link"><ArrowLeft/> Solicitudes</Link><h1>Conversaciones</h1><p>Acuerdos vinculados a solicitudes</p></div>
      <label className="chat-search"><Search/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar conversación"/></label>
      <label className="chat-unread-filter"><input type="checkbox" checked={unreadOnly} onChange={event=>setUnreadOnly(event.target.checked)}/> Solo no leídas</label>
      <nav className="conversation-list">{conversations.map(item=>{const related=providers.find(providerItem=>providerItem.id===item.providerId);const unread=item.unreadByProvider+item.unreadByRequester;return <Link key={item.id} to={`/requests/${item.id}/chat`} className={item.id===request.id?"active":""}><span className="conversation-avatar">{related?.publicName.slice(0,2).toUpperCase()}</span><span className="conversation-copy"><strong>{related?.publicName}</strong><b>{item.title}</b><small>{item.messages.at(-1)?.text}</small></span><span className="conversation-meta"><time>{new Date(item.updatedAt).toLocaleDateString("es-NI",{day:"numeric",month:"short"})}</time>{unread>0&&<em>{unread}</em>}</span></Link>})}</nav>
    </aside>
    <main className="chat-thread">
      <header className="chat-thread-header"><div><span className="conversation-avatar large">{provider.publicName.slice(0,2).toUpperCase()}</span><span><strong>{provider.publicName}</strong><small>{request.title}{offer?` · ${offer.name}`:""}</small></span></div><div className="chat-header-actions"><RequestStatusBadge status={request.status}/><label>Escribís como<select value={actor} onChange={event=>setActor(event.target.value as "provider"|"requester")}><option value="provider">Proveedor</option><option value="requester">Cliente</option></select></label><button className="icon-button" onClick={()=>setReportOpen(true)} aria-label="Reportar conversación"><Flag/></button></div></header>
      <details className="chat-mobile-summary"><summary>Resumen de la solicitud <ChevronDown/></summary><RequestSummary request={request} providerName={provider.publicName} offerName={offer?.name}/></details>
      <section className="retention-banner"><ShieldCheck/><div><strong>Conversación protegida</strong><p>Mantener el acuerdo acá permite dar seguimiento, confirmar el trabajo y desbloquear una reseña verificada.</p></div></section>
      <section className="message-stream" aria-live="polite">{request.messages.map(message=><article className="message-block-wrap" key={message.id}><MessageBlock message={message} providerName={provider.publicName} requesterName={request.requesterName}/></article>) }<div ref={bottomRef}/></section>
      {request.status!=="COMPLETED"&&!request.status.startsWith("CLOSED")&&<footer className="chat-composer">
        <div className="quick-replies">{quickReplies[actor].map(text=><button key={text} onClick={()=>setReply(text)}>{text}</button>)}</div>
        <div className="chat-quick-actions">{actor==="provider"&&<button onClick={()=>setQuoteOpen(!quoteOpen)}><HandCoins/> Enviar precio estimado</button>}<button onClick={()=>addMessage(request.id,actor==="provider"?"¿Podés compartir cantidad, medidas y fecha deseada?":"Te comparto los detalles necesarios para preparar la cotización.",actor,"QUICK_REPLY")}><FileText/> {actor==="provider"?"Pedir más detalles":"Enviar detalles"}</button><button onClick={()=>confirm(request.id,actor)}><CheckCheck/> Confirmar trabajo</button><button onClick={()=>setExternalOpen(true)}><AlertTriangle/> Contacto externo</button></div>
        {quoteOpen&&<form className="quote-composer" onSubmit={submitQuote}><div><strong>Enviar cotización en la conversación</strong><small>El precio y entrega quedarán vinculados a la solicitud.</small></div><input required value={price} onChange={event=>setPrice(event.target.value)} placeholder="Ej. C$1,200"/><input required value={delivery} onChange={event=>setDelivery(event.target.value)} placeholder="Ej. 5 días"/><button className="button primary"><Send/> Enviar cotización</button></form>}
        <form className="message-composer" onSubmit={submit}><textarea value={reply} onChange={event=>setReply(event.target.value)} placeholder="Escribí un mensaje con los detalles del acuerdo…" rows={2}/><button className="button primary" disabled={!reply.trim()} aria-label="Enviar mensaje"><Send/> Enviar</button></form>
      </footer>}
    </main>
    <aside className="chat-context"><RequestSummary request={request} providerName={provider.publicName} offerName={offer?.name}/><section className="chat-context-section"><h2>Próxima acción</h2>{request.status==="OPEN"&&<p>El proveedor debe responder para iniciar la negociación.</p>}{request.status==="IN_CONVERSATION"&&<p>Definan precio, alcance y fecha de entrega.</p>}{request.status==="QUOTE_SENT"&&<><p>La cotización espera respuesta del cliente.</p><button className="button primary full" onClick={()=>acceptQuote(request.id)}>Aceptar cotización</button></>}{request.status==="QUOTE_ACCEPTED"&&<p>El acuerdo está aceptado. Confirmen cuando el trabajo termine.</p>}{request.status==="COMPLETED"&&<p className="success-note"><BadgeCheck/> Reseña verificada desbloqueada.</p>}</section><section className="chat-context-section"><h2>Confirmación bilateral</h2><div className="confirmation-row"><span className={request.confirmedByRequesterAt?"done":""}>{request.confirmedByRequesterAt?<Check/>:<Circle/>} Cliente</span><span className={request.confirmedByProviderAt?"done":""}>{request.confirmedByProviderAt?<Check/>:<Circle/>} Proveedor</span></div>{request.status!=="COMPLETED"&&<><button className="button secondary full" disabled={!!request.confirmedByRequesterAt} onClick={()=>confirm(request.id,"requester")}>Confirmar como cliente</button><button className="button secondary full" disabled={!!request.confirmedByProviderAt} onClick={()=>confirm(request.id,"provider")}>Confirmar como proveedor</button><button className="text-button danger" onClick={()=>close(request.id,actor)}>Cerrar solicitud</button></>}</section></aside>
    {externalOpen&&<div className="dialog-backdrop"><section className="dialog"><div className="dialog-head"><div><span className="eyebrow">Protegé tu historial</span><h2>¿Salir de la conversación?</h2></div><button onClick={()=>setExternalOpen(false)}><X/></button></div><p>Podés continuar fuera de la app, pero esa conversación no contará para solicitudes completadas, reputación ni reseñas verificadas.</p><button className="button primary" onClick={()=>setExternalOpen(false)}>Seguir en la app</button><button className="button secondary" disabled>Contacto externo no disponible para el MVP</button></section></div>}
    {reportOpen&&<div className="dialog-backdrop"><form className="dialog" onSubmit={event=>{event.preventDefault();addReport({id:crypto.randomUUID(),reporterId:current.id,targetType:"REQUEST",targetId:request.id,reason:"Conversación sospechosa",description:reportText,status:"PENDING_REVIEW",createdAt:new Date().toISOString()});setReportOpen(false);setReportText("");}}><div className="dialog-head"><div><span className="eyebrow">Revisión humana</span><h2>Reportar conversación</h2></div><button type="button" onClick={()=>setReportOpen(false)}><X/></button></div><textarea required minLength={10} value={reportText} onChange={event=>setReportText(event.target.value)} placeholder="Explicá qué ocurrió"/><button className="button primary"><Flag/> Enviar reporte</button></form></div>}
  </div>;
}

function MessageBlock({message,providerName,requesterName}:{message:ChatMessage;providerName:string;requesterName:string}){if(message.author==="system")return <article className={`system-message type-${message.type.toLowerCase()}`}><Info/><div><strong>{message.type==="QUOTE_SUMMARY"?"Cotización":message.type==="REVIEW_UNLOCKED"?"Reseña desbloqueada":"Actualización"}</strong><p>{message.text}</p></div></article>;return <article className={`chat-message ${message.author}`}><div className="message-author"><strong>{message.author==="provider"?providerName:requesterName}</strong><time>{new Date(message.createdAt).toLocaleTimeString("es-NI",{hour:"2-digit",minute:"2-digit"})}</time></div><p>{message.text}</p>{message.type!=="TEXT"&&<small>{message.type.replaceAll("_"," ")}</small>}</article>}

function RequestSummary({request,providerName,offerName}:{request:ReturnType<typeof useMvpStore.getState>["requests"][number];providerName:string;offerName?:string}){return <section className="chat-context-section request-summary"><span className="eyebrow">Solicitud vinculada</span><h2>{request.title}</h2><p>{request.description}</p><dl><div><dt>Proveedor</dt><dd>{providerName}</dd></div>{offerName&&<div><dt>Oferta</dt><dd>{offerName}</dd></div>}<div><dt>Ubicación</dt><dd>{request.location||"Por acordar"}</dd></div><div><dt>Estado</dt><dd><RequestStatusBadge status={request.status}/></dd></div>{request.quotedPriceLabel&&<div><dt>Cotización</dt><dd>{request.quotedPriceLabel}</dd></div>}{request.quotedDeliveryTime&&<div><dt>Entrega</dt><dd>{request.quotedDeliveryTime}</dd></div>}</dl><Link className="text-link" to={`/requests/${request.id}`}>Ver detalle completo</Link></section>}
