import { Building2, CheckCircle2, Circle, FileCheck2, GraduationCap, Landmark, ShieldCheck } from "lucide-react";
import { useMvpStore } from "../stores/mvp-store";
import { FormalizationBadge, PageHeader } from "../components/mvp/Ui";

const steps=[{title:"Definir actividad económica",detail:"Describí qué vendés o qué servicio prestás."},{title:"Preparar identificación y domicilio",detail:"Reuní cédula y comprobante de domicilio."},{title:"Revisar inscripción tributaria",detail:"Consultá requisitos vigentes directamente con DGI."},{title:"Preparar registro MIPYME",detail:"Organizá la información solicitada por MIFIC."}];

export default function FormalizationPage(){
  const current=useMvpStore(state=>state.currentUser);const provider=useMvpStore(state=>state.providers.find(item=>item.id===state.currentUser.providerId));const saved=useMvpStore(state=>state.formalizationSteps[state.currentUser.providerId]);const toggle=useMvpStore(state=>state.toggleFormalizationStep);const completed=(saved??[true,true,false,false]).filter(Boolean).length;
  if(!provider)return <div className="content-page"><h1>Perfil no encontrado</h1></div>;
  const progress=saved??[true,true,false,false];
  return <div className="content-page"><PageHeader eyebrow="Guía de preparación" title="Tu ruta de formalización" description="Organizá los próximos pasos. Esta guía no reemplaza la orientación oficial ni se conecta con sistemas gubernamentales." actions={<FormalizationBadge status={provider.formalizationStatus}/>}/><div className="formalization-grid"><main><section className="content-section"><div className="section-heading"><h2>Checklist de preparación</h2><span>{completed} de {steps.length} completados</span></div><div className="progress"><span style={{width:`${completed/steps.length*100}%`}}/></div><div className="step-list">{steps.map((step,index)=><button key={step.title} onClick={()=>toggle(index)} aria-pressed={progress[index]}><span className={progress[index]?"done":""}>{progress[index]?<CheckCircle2/>:<Circle/>}</span><span><strong>{step.title}</strong>{step.detail}</span></button>)}</div><p className="form-note">Completar esta guía cambia tu estado a “En camino a MIPYME”. El badge “MIPYME formal” requiere revisión documental y no se concede automáticamente.</p></section><section className="content-section"><h2>Documentos para preparar</h2><ul className="document-list"><li><FileCheck2/> Cédula de identidad vigente</li><li><FileCheck2/> Comprobante de domicilio</li><li><FileCheck2/> Descripción de actividad económica</li><li><FileCheck2/> Información comercial y de contacto</li></ul></section></main><aside><section className="content-section"><h2>Instituciones de referencia</h2><div className="institution-list"><div><Landmark/><span><strong>MIFIC</strong>Registro y acompañamiento MIPYME.</span></div><div><Building2/><span><strong>DGI</strong>Registro tributario y obligaciones fiscales.</span></div><div><GraduationCap/><span><strong>INATEC</strong>Formación técnica y capacitación.</span></div></div></section><section className="benefit-panel"><ShieldCheck/><h2>¿Qué puede aportar?</h2><p>Más acceso a oportunidades, mejor organización y señales adicionales de confianza para clientes.</p></section></aside></div></div>;
}
