import { useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, Award, BadgeCheck, Bookmark, BriefcaseBusiness, CalendarCheck, Clock3, ExternalLink, Flag, MapPin, MessageCircle, Package, ShieldCheck, Star, X } from "lucide-react";
import { useMvpStore } from "../stores/mvp-store";
import { availabilityLabel, formalizationLabel, priceLabel, type OfferType } from "../lib/mvp-data";
import { EmptyState, FormalizationBadge, TrustBadge, VerificationBadge } from "../components/mvp/Ui";

const tabOptions:{value:"ALL"|OfferType;label:string}[]=[{value:"ALL",label:"Todos"},{value:"PRODUCT",label:"Productos"},{value:"SERVICE",label:"Servicios"},{value:"PACKAGE",label:"Paquetes"},{value:"PORTFOLIO_ITEM",label:"Portafolio"}];
const offerTypeLabel:Record<OfferType,string>={PRODUCT:"Producto",SERVICE:"Servicio",PACKAGE:"Paquete",PORTFOLIO_ITEM:"Portafolio"};

export default function ProviderPage(){
  const {providerId,id}=useParams(); const key=providerId||id; const provider=useMvpStore(state=>state.providers.find(item=>item.id===key)); const allReviews=useMvpStore(state=>state.reviews); const reviews=useMemo(()=>allReviews.filter(item=>item.providerId===key),[allReviews,key]); const allOffers=useMvpStore(state=>state.offers); const offers=useMemo(()=>allOffers.filter(item=>item.providerId===key&&item.status==="ACTIVE"),[allOffers,key]); const current=useMvpStore(state=>state.currentUser); const addReport=useMvpStore(state=>state.addReport);
  const [tab,setTab]=useState<"ALL"|OfferType>("ALL"); const [saved,setSaved]=useState(false); const [reportOpen,setReportOpen]=useState(false); const [reason,setReason]=useState("Perfil falso"); const [description,setDescription]=useState("");
  if(!provider)return <EmptyState title="Perfil no encontrado">Este proveedor no existe o ya no está disponible.</EmptyState>;
  const visibleOffers=offers.filter(offer=>tab==="ALL"||offer.type===tab); const avgReview=reviews.length?reviews.reduce((sum,item)=>sum+item.score,0)/reviews.length:null;
  return <div className="provider-page">
    <section className="provider-cover" style={{backgroundImage:`linear-gradient(90deg,rgba(14,35,31,.92),rgba(14,35,31,.25)),url(${provider.portfolioImages[0]})`}}><div><Link to="/search" className="back-link"><ArrowLeft/> Volver a resultados</Link><span className="eyebrow">{provider.category}</span><h1>{provider.publicName}</h1><p className="provider-tagline">Soluciones locales para negocios que necesitan avanzar con claridad.</p><div className="provider-identity-meta"><span><MapPin/>{provider.city}</span><span><CalendarCheck/>{availabilityLabel[provider.availability]}</span><span><Clock3/>Responde en {provider.responseTimeHrs} h</span></div><div className="badges"><TrustBadge score={provider.trustScore}/><VerificationBadge level={provider.verificationLevel}/><FormalizationBadge status={provider.formalizationStatus}/></div><div className="provider-primary-actions"><Link className="button primary" to={`/requests/new?providerId=${provider.id}`}><MessageCircle/> Chatear y solicitar cotización</Link><a className="button secondary" href="#ofertas"><Package/> Ver productos y servicios</a></div></div></section>
    <div className="provider-grid"><main><section className="content-section"><div className="section-heading"><h2>Acerca del negocio</h2><span>{provider.completedRequests} trabajos confirmados</span></div><p className="lead">{provider.description}</p><div className="business-facts"><div><span>Área de servicio</span><strong>{provider.city} y atención por acuerdo</strong></div><div><span>Tipo de negocio</span><strong>Proveedor local independiente</strong></div><div><span>Rango general</span><strong>{priceLabel[provider.priceRange]}</strong></div></div></section>
      <section className="content-section offers-public" id="ofertas"><div className="section-heading"><div><span className="eyebrow">Catálogo activo</span><h2>Productos y servicios</h2></div><span>{offers.length} ofertas disponibles</span></div><div className="offer-tabs">{tabOptions.map(option=><button className={tab===option.value?"active":""} onClick={()=>setTab(option.value)} key={option.value}>{option.label}<span>{option.value==="ALL"?offers.length:offers.filter(offer=>offer.type===option.value).length}</span></button>)}</div>{visibleOffers.length?<div className="public-offer-grid">{visibleOffers.map(offer=><article key={offer.id}><img src={offer.imageUrls[0]||provider.portfolioImages[0]} alt=""/><div><span className="eyebrow">{offerTypeLabel[offer.type]} · {offer.category}</span><h3>{offer.name}</h3><p>{offer.shortDescription}</p><dl><div><dt>Precio</dt><dd>{offer.priceLabel}</dd></div><div><dt>Entrega</dt><dd>{offer.estimatedDelivery||"Por acordar"}</dd></div>{offer.minimumOrder&&<div><dt>Mínimo</dt><dd>{offer.minimumOrder}</dd></div>}</dl><div className="card-actions"><Link className="button primary" to={`/requests/new?providerId=${provider.id}&productId=${offer.id}`}>Consultar por este producto</Link><Link className="button secondary" to={`/providers/${provider.id}/products/${offer.id}`}>Ver detalle</Link></div></div></article>)}</div>:<EmptyState icon={<Package/>} title="No hay ofertas en esta categoría">Podés enviar una solicitud general desde el perfil.</EmptyState>}</section>
      <section className="content-section"><div className="section-heading"><h2>Reseñas verificadas</h2><span>{avgReview?`${avgReview.toFixed(1)} de 5 · `:""}{reviews.length} experiencias</span></div>{reviews.length?reviews.map(review=><article className="review" key={review.id}><div><span className="stars">{Array.from({length:review.score},(_,index)=><Star key={index}/>)}</span><time>{new Date(review.createdAt).toLocaleDateString("es-NI")}</time></div><p>{review.text}</p><small><BadgeCheck/> Trabajo confirmado por ambas partes</small></article>):<EmptyState title="Todavía no hay reseñas verificadas">Iniciá una solicitud dentro de la app para dejar una reseña cuando el trabajo se complete.</EmptyState>}</section></main>
      <aside className="profile-sidebar"><section><h2><ShieldCheck/> Confianza y reputación</h2><strong className="big-score">{provider.trustScore}<small>/100</small></strong><p>Se calcula con solicitudes completadas dentro de la plataforma, reseñas verificadas y nivel del perfil. Las conversaciones externas no suman al historial.</p><dl><div><dt>Verificación</dt><dd>{provider.verificationLevel}</dd></div><div><dt>Trabajos bilaterales</dt><dd>{provider.completedRequests}</dd></div><div><dt>Reseña promedio</dt><dd>{avgReview?.toFixed(1)||"Sin reseñas"}</dd></div></dl><Link className="text-link" to="/trust">Cómo funciona la confianza</Link></section><section><h2><Award/> Medallas</h2><div className="medal-list">{provider.medals.map(medal=><span key={medal}><Award/>{medal}</span>)}</div></section><section><h2><BriefcaseBusiness/> Formalización</h2><FormalizationBadge status={provider.formalizationStatus}/><p>{provider.formalizationStatus==="MIPYME"?"Este negocio muestra estado MIPYME formal.":provider.formalizationStatus==="IN_PROGRESS"?"Está organizando su información para avanzar en formalización.":"Puede usar la guía para preparar su proceso de formalización."}</p><Link className="text-link" to="/formalization">Ver guía de formalización</Link></section><section><h2>Acciones</h2><button className="button secondary full" onClick={()=>setSaved(!saved)}><Bookmark/>{saved?"Proveedor guardado":"Guardar proveedor"}</button>{current.providerId===provider.id&&<Link className="button secondary full" to="/me/profile/edit">Editar mi perfil público</Link>}<button className="button secondary full" disabled title="No disponible para el MVP"><ExternalLink/> Compartir no disponible</button><button className="text-button danger" onClick={()=>setReportOpen(true)}><Flag/> Reportar perfil</button></section></aside></div>
    {reportOpen&&<div className="dialog-backdrop" onMouseDown={()=>setReportOpen(false)}><form className="dialog" onMouseDown={event=>event.stopPropagation()} onSubmit={event=>{event.preventDefault();addReport({id:crypto.randomUUID(),reporterId:current.id,targetType:"PROVIDER",targetId:provider.id,reason,description,status:"PENDING_REVIEW",createdAt:new Date().toISOString()});setReportOpen(false);}}><div className="dialog-head"><div><span className="eyebrow">Revisión humana</span><h2>Reportar perfil</h2></div><button type="button" onClick={()=>setReportOpen(false)}><X/></button></div><label>Motivo<select value={reason} onChange={event=>setReason(event.target.value)}><option>Perfil falso</option><option>Calificación sospechosa</option><option>Spam</option><option>Contenido inapropiado</option><option>Intento de estafa</option><option>Otro</option></select></label><label>Descripción<textarea required minLength={10} value={description} onChange={event=>setDescription(event.target.value)} placeholder="Contanos qué ocurrió"/></label><p className="form-note">No se aplicarán sanciones automáticas. Una persona revisará el reporte.</p><button className="button primary">Enviar reporte</button></form></div>}
  </div>;
}
